sonar.organization=austek
sonar.projectKey=austek_pact-avro-plugin
sonar.sources=modules/plugin/src/main/scala
sonar.tests=modules/plugin/src/test/scala
sonar.sourceEncoding=UTF-8
sonar.scala.coverage.reportPaths=modules/plugin/target/scala-3.8.4/scoverage-report/scoverage.xml
