= Testing

For an overview how asynchronous messages work with Pact, see https://docs.pact.io/getting_started/how_pact_works/#non-http-testing-message-pact[Non-HTTP testing (Message Pact)].

In this scenario, a message provider writes an Avro message to some one-way transport mechanism, like a message queue, and a consumer
then reads it. With this style of testing, the transport mechanism is abstracted away.

== Consumer

The message consumer test is written using the Pact Message test DSL. The test DSL defines the expected message format,  and then the consumer is tested with an example message generated by the test framework.

== The Avro test configuration

The consumer tests need to get the plugin loaded and configure the expected messages to use in the test. This is done
using the `usingPlugin` (or `using_plugin`, depending on the language implementation) followed by the content for the test
in some type of map form.

For each field of the message that we want in the contract, we define an entry with the field name as the key and
a matching definition as the value. For documentation on the matching definition format, see https://github.com/pact-foundation/pact-plugins/blob/main/docs/matching-rule-definition-expressions.md[Matching Rule definition expressions].

For example, we would use the `pact_consumer` `PactBuilder`:

.Example Avro schema
[%collapsible]
====
[source,avroschema]
----
include::example$plugin-rs/tests/fixtures/e2e/orders.avsc[]
----
====

.Consumer configuration
[source,rust]
----
include::example$plugin-rs/tests/e2e_consumer.rs[tags=configuration]
----


.Rust example consumer test
[source,rust]
----
include::example$plugin-rs/tests/e2e_consumer.rs[tags=consumer_test]
----

== Provider

The message provider is verified by getting it to generate a message, and then this is verified against the Pact file
from the consumer. There are two main ways of verifying the provider:

. Write a test in the provider code base that can call the provider to generate the message.
. Use an HTTP proxy server that can call the provider and return the generated message, and then use a Pact framework verifier to verify it.

.Rust example provider test
[%collapsible]
====
[source,rust]
----
include::example$plugin-rs/tests/e2e_provider.rs[]
----
====
