addSbtPlugin("com.github.sbt"       % "sbt-git"               % "2.1.0")
addSbtPlugin("com.github.sbt"       % "sbt-github-actions"    % "0.24.0")
addSbtPlugin("com.github.sbt"       % "sbt-native-packager"   % "1.11.0")
addSbtPlugin("com.github.sbt.junit" % "sbt-jupiter-interface" % "0.13.3")
addSbtPlugin("com.lightbend.sbt"    % "sbt-java-formatter"    % "0.8.0")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"          % "2.5.2")
addSbtPlugin("org.typelevel"        % "sbt-tpolecat"          % "0.5.2")
