addSbtPlugin("com.github.sbt"       % "sbt-git"               % "2.1.0")
addSbtPlugin("com.github.sbt"       % "sbt-github-actions"    % "0.31.0")
addSbtPlugin("com.github.sbt"       % "sbt-native-packager"   % "1.11.7")
addSbtPlugin("com.github.sbt.junit" % "sbt-jupiter-interface" % "0.19.0")
addSbtPlugin("com.github.sbt"       % "sbt-java-formatter"    % "0.13.1")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"          % "2.6.2")
addSbtPlugin("org.typelevel"        % "sbt-tpolecat"          % "0.5.7")
